// Utility to clean and format event descriptions
export function sanitizeDescription(html: string): string {
  if (!html) return '';
  // Decode HTML entities
  const decoded = html
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'");
  // Remove HTML tags
  const stripped = decoded.replace(/<[^>]*>/g, '');
  // Clean up extra whitespace
  return stripped
    .replace(/\s+/g, ' ')
    .trim()
    .substring(0, 300); // Limit to 300 chars
}

// Comprehensive translation from Japanese to English
export function translateToEnglish(text: string): string {
  if (!text) return '';
  
  // Comprehensive Japanese to English translations with extensive kanji and hiragana coverage
  const translations: Record<string, string> = {
    // ============ HIRAGANA (All basic characters and common phrases) ============
    // Basic hiragana characters
    'あ': 'a',
    'い': 'i',
    'う': 'u',
    'え': 'e',
    'お': 'o',
    'か': 'ka',
    'き': 'ki',
    'く': 'ku',
    'け': 'ke',
    'こ': 'ko',
    'が': 'ga',
    'ぎ': 'gi',
    'ぐ': 'gu',
    'げ': 'ge',
    'ご': 'go',
    'さ': 'sa',
    'し': 'si/shi',
    'す': 'su',
    'せ': 'se',
    'そ': 'so',
    'ざ': 'za',
    'じ': 'ji',
    'ず': 'zu',
    'ぜ': 'ze',
    'ぞ': 'zo',
    'た': 'ta',
    'ち': 'chi',
    'つ': 'tsu',
    'て': 'te',
    'と': 'to',
    'だ': 'da',
    'ぢ': 'di',
    'づ': 'du',
    'で': 'de',
    'ど': 'do',
    'な': 'na',
    'に': 'ni',
    'ぬ': 'nu',
    'ね': 'ne',
    'の': 'no',
    'は': 'ha',
    'ひ': 'hi',
    'ふ': 'fu',
    'へ': 'he',
    'ほ': 'ho',
    'ば': 'ba',
    'び': 'bi',
    'ぶ': 'bu',
    'べ': 'be',
    'ぼ': 'bo',
    'ぱ': 'pa',
    'ぴ': 'pi',
    'ぷ': 'pu',
    'ぺ': 'pe',
    'ぽ': 'po',
    'ま': 'ma',
    'み': 'mi',
    'む': 'mu',
    'め': 'me',
    'も': 'mo',
    'や': 'ya',
    'ゆ': 'yu',
    'よ': 'yo',
    'ら': 'ra',
    'り': 'ri',
    'る': 'ru',
    'れ': 're',
    'ろ': 'ro',
    'わ': 'wa',
    'ゐ': 'wi',
    'ゑ': 'we',
    'を': 'wo',
    'ん': 'n',
    
    // Common hiragana words and phrases
    '帰ってきた': 'Returned',
    '帰る': 'Return',
    '帰り': 'Return',
    '事業': 'Business',
    '事業停止': 'Business Suspension',
    '停止': 'Suspension',
    '危機': 'Crisis',
    '救え': 'Save',
    '救う': 'Save',
    '救える': 'Can Save',
    'サメシャイン': 'Shark Shine',
    'シャイン': 'Shine',
    '水族館': 'Aquarium',
    'こと': 'Thing',
    '発生': 'Occurred',
    'してしまいました': 'Happened',
    'てください': 'Please',
    'てほしい': 'Want you to',
    'ているところです': 'Currently',
    'ているため': 'Because',
    'ているので': 'Because',
    'ているから': 'Because',
    'ている': 'Is doing',
    'ていた': 'Was doing',
    'ていない': 'Not doing',
    'た': 'Did',
    'たり': 'Or',
    'たちは': 'We',
    'たち': 'Ones',
    'ただし': 'However',
    'ただ': 'Only',
    'ため': 'For',
    'ための': 'For',
    'たのは': 'What',
    'たので': 'So',
    'たことが': 'Experience',
    'たから': 'Because did',
    'たのか': 'Did',
    'たらいい': 'Would be good',
    'たらどう': 'What if',
    'たら': 'If',
    'だろう': 'Probably',
    'だろうか': 'Probably',
    'だろうね': 'Probably',
    'だったら': 'If',
    'だったら': 'In that case',
    'だったり': 'Sometimes',
    'だった': 'Was',
    'だったよ': 'Was',
    'だったのか': 'Was',
    'だったのは': 'Was',
    'だったので': 'So',
    'だったから': 'Because was',
    'だったこと': 'What was',
    'だけで': 'Just by',
    'だけで': 'Only',
    'だけに': 'Only',
    'だけは': 'At least',
    'だけ': 'Only',
    'だから': 'So',
    'だから': 'Therefore',
    'だからこそ': 'That is why',
    'だがしかし': 'However',
    'だが': 'But',
    'だと': 'If',
    'だとしたら': 'If so',
    'だとしても': 'Even if',
    'だとすると': 'If',
    'だとおもう': 'I think',
    'だとは': 'That',
    'だとはかぎらない': 'Not necessarily',
    'だとわかる': 'Can tell',
    'だとしても': 'Even so',
    'だって': 'But',
    'だって': 'Because',
    'だって': 'Even',
    'だっけ': 'Was it',
    'だったっけ': 'Was it',
    'だっけど': 'But',
    'だとか': 'Like',
    'だの': 'Or something',
    'だわ': 'It is',
    'だね': 'Right',
    'だよ': 'You know',
    'だよね': 'Right',
    'だな': 'I see',
    'だな': 'Looks like',
    'だな': 'Seems',
    'だのに': 'Yet',
    'だのに': 'And yet',
    'などなど': 'And so on',
    'など': 'Such as',
    'など': 'Etc',
    'など': 'Things like',
    'なんて': 'Such as',
    'なんて': 'Like',
    'なんて': 'No way',
    'なんか': 'Something',
    'なんか': 'Like',
    'なんか': 'Or something',
    'なんで': 'Why',
    'なんで': 'How come',
    'なんに': 'What',
    'なんぞ': 'Such things',
    'なんだ': 'What',
    'なんだろう': 'What is',
    'なんだか': 'Something',
    'なんだか': 'Somehow',
    'なんだかない': 'Something is wrong',
    'なんだった': 'What was',
    'なんだっけ': 'What was',
    'なんだから': 'So',
    'なんだし': 'And',
    'なんだし': 'Anyway',
    'なんだし': 'Since',
    'なんだと': 'What is',
    'なんだよ': 'What is',
    'なんだよ': 'You know',
    'なんだよね': 'You know',
    'なんだわ': 'It is',
    '向こう': 'Over there',
    '何か': 'Something',
    '何か': 'Anything',
    '何の': 'What',
    '何の': 'What kind of',
    '何ぞ': 'Such',
    '何も': 'Nothing',
    '何も': 'None',
    '何も彼も': 'Everything',
    '何やら': 'Something',
    '何やら': 'Some kind of',
    '何や': 'Something',
    '何や': 'Various',
    '何と': 'What',
    '何と': 'How',
    '何と': 'Surprisingly',
    '何たる': 'What kind of',
    '何たる': 'What',
    '何だ': 'What is',
    '何だろう': 'What is',
    '何だか': 'Something',
    '何だか': 'Somehow',
    '何だから': 'So',
    '何だって': 'What',
    '何だって': 'How',
    '何だって': 'Anything',
    '何だって': 'Whatever',
    '何だって': 'So what',
    '何だとか': 'Something like',
    
    // ============ COMMON KANJI (Joyo Kanji) ============
    // Numbers
    '一': 'One',
    '二': 'Two',
    '三': 'Three',
    '四': 'Four',
    '五': 'Five',
    '六': 'Six',
    '七': 'Seven',
    '八': 'Eight',
    '九': 'Nine',
    '十': 'Ten',
    '百': 'Hundred',
    '千': 'Thousand',
    '万': 'Ten Thousand',
    '円': 'Yen',
    
    // Time-related kanji
    '年': 'Year',
    '月': 'Month',
    '日': 'Day',
    '時': 'Time',
    '分': 'Minute',
    '秒': 'Second',
    '週': 'Week',
    '曜': 'Day of Week',
    '朝': 'Morning',
    '昼': 'Noon',
    '夜': 'Night',
    '今': 'Now',
    '過去': 'Past',
    '未来': 'Future',
    '春': 'Spring',
    '夏': 'Summer',
    '秋': 'Fall',
    '冬': 'Winter',
    '季': 'Season',
    '始': 'Begin',
    '終': 'End',
    '始まる': 'Start',
    '終わる': 'End',
    '前': 'Before',
    '後': 'After',
    '早い': 'Early',
    '遅い': 'Late',
    
    // People-related kanji
    '人': 'Person',
    '男': 'Man',
    '女': 'Woman',
    '子': 'Child',
    '親': 'Parent',
    '兄': 'Older Brother',
    '弟': 'Younger Brother',
    '姉': 'Older Sister',
    '妹': 'Younger Sister',
    '夫': 'Husband',
    '妻': 'Wife',
    '友': 'Friend',
    '者': 'Person/One',
    '先生': 'Teacher',
    '学生': 'Student',
    '医者': 'Doctor',
    '社員': 'Employee',
    '会社員': 'Company Employee',
    '職': 'Job',
    '職業': 'Occupation',
    '団': 'Group',
    
    // Place-related kanji
    '国': 'Country',
    '都': 'Metropolis',
    '府': 'Prefecture',
    '県': 'Prefecture',
    '市': 'City',
    '区': 'Ward',
    '町': 'Town',
    '村': 'Village',
    '路': 'Road',
    '街': 'Street',
    '駅': 'Station',
    '港': 'Harbor',
    '空港': 'Airport',
    '場': 'Place',
    '会場': 'Venue',
    '地': 'Earth/Place',
    '所': 'Place',
    '家': 'House',
    '建物': 'Building',
    '館': 'Hall',
    '室': 'Room',
    '部屋': 'Room',
    '階': 'Floor',
    '層': 'Layer',
    '台': 'Platform',
    '公園': 'Park',
    '庭': 'Garden',
    '池': 'Pond',
    '川': 'River',
    '山': 'Mountain',
    '峰': 'Peak',
    '丘': 'Hill',
    '谷': 'Valley',
    '平': 'Plain',
    '地域': 'Area',
    '地方': 'Region',
    '土地': 'Land',
    '敷地': 'Site',
    
    // Major cities & locations
    '東京': 'Tokyo',
    '大阪': 'Osaka',
    '京都': 'Kyoto',
    '札幌': 'Sapporo',
    '福岡': 'Fukuoka',
    '横浜': 'Yokohama',
    '神戸': 'Kobe',
    '広島': 'Hiroshima',
    '名古屋': 'Nagoya',
    '川崎': 'Kawasaki',
    '福山': 'Fukuyama',
    '岡山': 'Okayama',
    '金沢': 'Kanazawa',
    '仙台': 'Sendai',
    '新潟': 'Niigata',
    '長野': 'Nagano',
    '松本': 'Matsumoto',
    '浜松': 'Hamamatsu',
    '沼津': 'Numazu',
    '岡崎': 'Okazaki',
    '豊田': 'Toyota',
    '四日市': 'Yokkaichi',
    '津': 'Tsu',
    '和歌山': 'Wakayama',
    '奈良': 'Nara',
    '大津': 'Otsu',
    '兵庫': 'Hyogo',
    '姫路': 'Himeji',
    '尼崎': 'Amagasaki',
    '明石': 'Akashi',
    '淡路': 'Awaji',
    '高松': 'Takamatsu',
    '徳島': 'Tokushima',
    '松山': 'Matsuyama',
    '高知': 'Kochi',
    '福岡市': 'Fukuoka City',
    '北九州': 'Kitakyushu',
    '久留米': 'Kurume',
    '有馬': 'Arima',
    '伊豆': 'Izu',
    '箱根': 'Hakone',
    '日光': 'Nikko',
    '富士': 'Fuji',
    
    // University and educational institutions
    '大学': 'University',
    '大学院': 'Graduate School',
    '学校': 'School',
    '高校': 'High School',
    '中学': 'Junior High',
    '小学': 'Elementary School',
    '図書館': 'Library',
    '講堂': 'Lecture Hall',
    '教室': 'Classroom',
    '研究室': 'Research Lab',
    '駒澤大学': 'Komadzawa University',
    '駒沢キャンパス': 'Komadzawa Campus',
    '種月館': 'Tanemono Building',
    '号館': 'Building',
    
    // Action verbs (kanji)
    '行く': 'Go',
    '来る': 'Come',
    '行う': 'Conduct',
    '実施': 'Conduct',
    '開始': 'Start',
    '開く': 'Open',
    '始まる': 'Begin',
    '始める': 'Begin',
    '終わる': 'End',
    '終える': 'End',
    '終了': 'End',
    '作る': 'Make',
    '作成': 'Create',
    '見る': 'See',
    '聞く': 'Listen',
    '話す': 'Talk',
    '言う': 'Say',
    '読む': 'Read',
    '書く': 'Write',
    '編集': 'Edit',
    '修正': 'Correct',
    '改善': 'Improve',
    '変更': 'Change',
    '移す': 'Move',
    '置く': 'Place',
    '配置': 'Arrange',
    '記す': 'Record',
    '登録': 'Register',
    '参加': 'Participate',
    '出席': 'Attend',
    '欠席': 'Absent',
    '遅刻': 'Late',
    '到着': 'Arrive',
    '出発': 'Depart',
    '帰宅': 'Return Home',
    '立つ': 'Stand',
    '座る': 'Sit',
    '寝る': 'Sleep',
    '起きる': 'Wake',
    '働く': 'Work',
    '休む': 'Rest',
    '連絡': 'Contact',
    '確認': 'Confirm',
    '報告': 'Report',
    '質問': 'Question',
    '答える': 'Answer',
    '説明': 'Explain',
    '理解': 'Understand',
    '学ぶ': 'Learn',
    '教える': 'Teach',
    '知る': 'Know',
    '思う': 'Think',
    '考える': 'Think',
    '信じる': 'Believe',
    '望む': 'Hope',
    '求める': 'Seek',
    '提供': 'Offer',
    '与える': 'Give',
    '受ける': 'Receive',
    '取る': 'Take',
    '持つ': 'Hold',
    '入れる': 'Put In',
    '出す': 'Take Out',
    '追加': 'Add',
    '削除': 'Delete',
    '接続': 'Connect',
    '利用': 'Use',
    '関係': 'Related',
    '設定': 'Set',
    '調整': 'Adjust',
    '検查': 'Check',
    '検定': 'Verify',
    '承認': 'Approve',
    '許可': 'Permit',
    '禁止': 'Prohibit',
    
    // Adjectives (kanji)
    '新しい': 'New',
    '古い': 'Old',
    '大きい': 'Big',
    '小さい': 'Small',
    '長い': 'Long',
    '短い': 'Short',
    '高い': 'High',
    '低い': 'Low',
    '強い': 'Strong',
    '弱い': 'Weak',
    '熱い': 'Hot',
    '冷たい': 'Cold',
    '美しい': 'Beautiful',
    '醜い': 'Ugly',
    '良い': 'Good',
    '悪い': 'Bad',
    '多い': 'Many',
    '少ない': 'Few',
    '深い': 'Deep',
    '浅い': 'Shallow',
    '厚い': 'Thick',
    '薄い': 'Thin',
    '広い': 'Wide',
    '狭い': 'Narrow',
    '近い': 'Near',
    '遠い': 'Far',
    '上': 'Up',
    '下': 'Down',
    '右': 'Right',
    '左': 'Left',
    '中': 'Middle',
    '外': 'Outside',
    '内': 'Inside',
    '前': 'Front',
    '後': 'Back',
    '東': 'East',
    '西': 'West',
    '南': 'South',
    '北': 'North',
    '重い': 'Heavy',
    '軽い': 'Light',
    '真': 'True',
    '偽': 'False',
    '正': 'Correct',
    '負': 'Negative',
    '勝': 'Win',
    '敗': 'Lose',
    '成功': 'Success',
    '失敗': 'Failure',
    '完全': 'Perfect',
    '不完全': 'Imperfect',
    '可能': 'Possible',
    '不可能': 'Impossible',
    '簡単': 'Easy',
    '難': 'Difficulty',
    '難しい': 'Difficult',
    '複雑': 'Complex',
    '単純': 'Simple',
    
    // Event types and categories
    'イベントの詳細': 'Event Details',
    'イベント詳細': 'Event Details',
    'イベント': 'Event',
    '行事': 'Event',
    '催し': 'Event',
    '行事': 'Ceremony',
    '【対面】': '[In-Person]',
    '【初心者向け】': '[Beginner-Friendly]',
    'Open Source Conference': 'Open Source Conference',
    'マネジメント': 'Management',
    'ワークショップ': 'Workshop',
    'ハンズオン': 'Hands-on',
    'カンファレンス': 'Conference',
    'セミナー': 'Seminar',
    'シンポジウム': 'Symposium',
    '講演': 'Lecture',
    'トーク': 'Talk',
    'ディスカッション': 'Discussion',
    '基礎': 'Basics',
    '入門': 'Introduction',
    '初級': 'Beginner',
    '中級': 'Intermediate',
    '上級': 'Advanced',
    '実践': 'Practical',
    '応用': 'Applied',
    '講座': 'Course',
    '講習': 'Training',
    '研修': 'Training Program',
    'パフォーマンス': 'Performance',
    'プレゼンテーション': 'Presentation',
    '懇親会': 'Networking',
    'パーティー': 'Party',
    'ポップアップ': 'Pop-up',
    '展示': 'Exhibition',
    '展示会': 'Trade Show',
    'エクスポ': 'Expo',
    
    // Event attributes
    '2日間': '2-Day',
    '3日間': '3-Day',
    '4日間': '4-Day',
    '5日間': '5-Day',
    '1泊': '1-Night',
    '2泊': '2-Night',
    '3泊': '3-Night',
    '1時間': '1-Hour',
    '2時間': '2-Hour',
    '3時間': '3-Hour',
    '4時間': '4-Hour',
    '5時間': '5-Hour',
    '終日': 'All-Day',
    '全日': 'Full-Day',
    'オンライン': 'Online',
    'ハイブリッド': 'Hybrid',
    'オフライン': 'Offline',
    
    // Kanji terms - Content and documentation
    '日本語版': 'Japanese Version',
    '日本語': 'Japanese Language',
    '言語': 'Language',
    'Web技術': 'Web Technology',
    'Web関連': 'Web-related',
    'Web': 'Web',
    'ドキュメント': 'Documentation',
    'ドキュメントの編集': 'Documentation Editing',
    'ルート': 'Route',
    'お手軽ルート': 'Easy Route',
    '手順': 'Instructions',
    '技術': 'Technology',
    'テクノロジー': 'Technology',
    '興味': 'Interest',
    'に興味': 'Interested in',
    '経験': 'Experience',
    '英語力': 'English Ability',
    '英語': 'English',
    '中国語': 'Chinese',
    '韓国語': 'Korean',
    'スペイン語': 'Spanish',
    'フランス語': 'French',
    '対象': 'Target',
    'コントリビューション': 'Contribution',
    '作業': 'Work',
    '関連': 'Related',
    'に関連': 'Related to',
    '編集': 'Editing',
    '編集の仕方': 'Editing Method',
    '仕方': 'Method',
    '体験': 'Experience',
    'できるハンズオン': 'Hands-on Experience',
    '当日': 'Day of Event',
    'お越し': 'Come',
    '従い': 'Follow',
    'に従い': 'In Accordance With',
    '出来れば': 'If you can',
    '問いません': 'Not Required',
    '来場': 'Attendance',
    '会場': 'Venue',
    '場所': 'Location',
    '住所': 'Address',
    '地点': 'Location',
    '開始': 'Start',
    '開始時間': 'Start Time',
    '開始日': 'Start Date',
    '開く': 'Open',
    '終了': 'End',
    '終了時間': 'End Time',
    '終了日': 'End Date',
    '開催': 'Held',
    '開催日': 'Event Date',
    '開催地': 'Event Location',
    '中止': 'Cancelled',
    '延期': 'Postponed',
    
    // Topics and skills
    'プログラミング': 'Programming',
    '開発': 'Development',
    'フロントエンド': 'Frontend',
    'バックエンド': 'Backend',
    'フルスタック': 'Full Stack',
    '設計': 'Design',
    'UI': 'UI',
    'UX': 'UX',
    'デザイン': 'Design',
    'JavaScript': 'JavaScript',
    'Python': 'Python',
    'TypeScript': 'TypeScript',
    'Java': 'Java',
    'C++': 'C++',
    'Ruby': 'Ruby',
    'Go': 'Go',
    'Rust': 'Rust',
    'React': 'React',
    'Vue': 'Vue',
    'Angular': 'Angular',
    'Node.js': 'Node.js',
    'Express': 'Express',
    'Django': 'Django',
    'Flask': 'Flask',
    'Webシステム': 'Web Systems',
    'web': 'web',
    'クラウド': 'Cloud',
    'AWS': 'AWS',
    'Azure': 'Azure',
    'GCP': 'GCP',
    'AI': 'AI',
    '機械学習': 'Machine Learning',
    'データベース': 'Database',
    'SQL': 'SQL',
    'NoSQL': 'NoSQL',
    'セキュリティ': 'Security',
    'サイバー': 'Cyber',
    'DevOps': 'DevOps',
    'Git': 'Git',
    'GitHub': 'GitHub',
    'GitLab': 'GitLab',
    'Docker': 'Docker',
    'Kubernetes': 'Kubernetes',
    'CI・CD': 'CI/CD',
    'テスト': 'Testing',
    'デバッグ': 'Debugging',
    '品質': 'Quality',
    'パフォーマンス': 'Performance',
    'スケーラビリティ': 'Scalability',
    '保守性': 'Maintainability',
    'アーキテクチャ': 'Architecture',
    'マイクロサービス': 'Microservices',
    'API': 'API',
    'REST': 'REST',
    'GraphQL': 'GraphQL',
    'JSON': 'JSON',
    'XML': 'XML',
    'HTML': 'HTML',
    'CSS': 'CSS',
    'SCSS': 'SCSS',
    'Sass': 'Sass',
    'Tailwind': 'Tailwind',
    'Bootstrap': 'Bootstrap',
    'モバイル': 'Mobile',
    'iOS': 'iOS',
    'Android': 'Android',
    'ネイティブアプリ': 'Native App',
    'ハイブリッドアプリ': 'Hybrid App',
    'PWA': 'PWA',
    'VR': 'VR',
    'AR': 'AR',
    'IoT': 'IoT',
    'ブロックチェーン': 'Blockchain',
    'NFT': 'NFT',
    'スマートコントラクト': 'Smart Contract',
    'Web3': 'Web3',
    'MDN': 'MDN',
    'Browser': 'Browser',
    'ブラウザ': 'Browser',
    'Chrome': 'Chrome',
    'Firefox': 'Firefox',
    'Safari': 'Safari',
    'Edge': 'Edge',
    
    // Business & organization
    'JAWS': 'JAWS',
    'OSC': 'Open Source Conference',
    'GitHub サイト': 'GitHub Site',
    'GitHub上': 'On GitHub',
    'GitHubサイト': 'GitHub Site',
    'GitHub でのコントリビューション': 'GitHub Contributions',
    '公式サイト': 'Official Website',
    '公式websiteサイト': 'Official Website',
    '公式Facebook': 'Official Facebook',
    'Facebook': 'Facebook',
    'Twitter': 'Twitter',
    'Instagram': 'Instagram',
    'LINE': 'LINE',
    'Slack': 'Slack',
    'Discord': 'Discord',
    '主催': 'Organizer',
    '主催者': 'Host',
    '主催': 'Held By',
    '出演': 'Performance',
    '出演者': 'Performer',
    '展開': 'Exhibit',
    '展開者': 'Exhibitor',
    '実行委員会': 'Organizing Committee',
    '委員': 'Committee Member',
    '委員会': 'Committee',
    '協会': 'Association',
    '協力': 'Cooperation',
    '協力者': 'Cooperator',
    '団体': 'Group',
    '団体名': 'Group Name',
    '法人': 'Organization',
    'NGO': 'NGO',
    'NPO': 'NPO',
    'サークル': 'Circle',
    'クラブ': 'Club',
    '同好会': 'Hobby Club',
    
    // Audience & participation
    '募集対象': 'Target Audience',
    '一般参加者': 'General Participants',
    '一般チケット': 'General Ticket',
    '学生': 'Student',
    '学生割': 'Student Discount',
    '学生料金': 'Student Price',
    '個人': 'Individual',
    '企業': 'Corporate',
    'コーポレート': 'Corporate',
    '団体': 'Group',
    '団体割': 'Group Discount',
    '子供': 'Child',
    '大人': 'Adult',
    '高齢者': 'Senior',
    'Individual Supporters': 'Individual Supporters',
    '参加': 'Participation',
    '参加者': 'Participant',
    '参加費': 'Admission Fee',
    '参加料': 'Admission Fee',
    'チケット': 'Ticket',
    'チケット代': 'Ticket Price',
    'チケット価格': 'Ticket Price',
    '前売': 'Advance Sale',
    '前売券': 'Advance Ticket',
    '当日': 'Day of Event',
    '当日チケット': 'Day of Event Ticket',
    '当日券': 'Day of Event Ticket',
    '無料': 'Free',
    '無料チケット': 'Free Ticket',
    '有料': 'Paid',
    '有料チケット': 'Paid Ticket',
    '登録': 'Registration',
    '登録料': 'Registration Fee',
    'の登録': 'Registration',
    '申し込み': 'Application',
    '申込': 'Application',
    '申し込み方法': 'How to Apply',
    '申し込み期間': 'Application Period',
    '申し込み期限': 'Application Deadline',
    '期限': 'Deadline',
    '締切': 'Deadline',
    '期間': 'Period',
    '期間中': 'During the Period',
    '予約': 'Reservation',
    '予約受付': 'Accepting Reservations',
    '待機': 'Waiting',
    'キャンセル': 'Cancellation',
    'キャンセル待ち': 'Waiting List',
    '確認': 'Confirm',
    '確定': 'Confirmed',
    '仮予約': 'Provisional Reservation',
    'メール': 'Email',
    'メールで': 'By Email',
    '直接': 'Direct',
    '現地': 'On-site',
    'オンライン登録': 'Online Registration',
    
    // Additional common terms
    '程度': 'Degree',
    'ぐらい': 'About',
    'くらい': 'About',
    '位': 'Position',
    '性': 'Type',
    '的': 'Style',
    '度': 'Degree',
    '量': 'Amount',
    '質': 'Quality',
    '率': 'Rate',
    '数': 'Number',
    '件': 'Items',
    'つ': 'Items',
    'コ': 'Items',
    '個': 'Items',
    '種': 'Type',
    '類': 'Type',
    '名': 'Name',
    '式': 'Type',
    '型': 'Type',
    '版': 'Version',
    'バージョン': 'Version',
    'エディション': 'Edition',
    '版': 'Edition',
    '形': 'Form',
    '形態': 'Form',
    '方式': 'Method',
    '順': 'Order',
    '序': 'Sequence',
    '部': 'Section',
    '章': 'Chapter',
    '節': 'Section',
    '段': 'Paragraph',
    '列': 'Column',
    '行': 'Row',
    '表': 'Table',
    '図': 'Figure',
    '段落': 'Paragraph',
    '本文': 'Main Text',
    '題目': 'Title',
    'タイトル': 'Title',
    '見出し': 'Heading',
    '説明': 'Explanation',
    '説明書': 'Manual',
    '指南': 'Guidance',
    '例': 'Example',
    '事例': 'Case',
    '参考': 'Reference',
    '付録': 'Appendix',
    '別紙': 'Attachment',
    'テンプレート': 'Template',
    'サンプル': 'Sample',
    'デモ': 'Demo',
    
    // ============ HIRAGANA PATTERNS & VERB CONJUGATIONS ============
    'ることがあります': 'Sometimes',
    'ることができます': 'Can',
    'ることができません': 'Cannot',
    'ことができます': 'Can',
    'ことができません': 'Cannot',
    'ことがあります': 'Sometimes',
    'ことになります': 'Will have to',
    'ことになるでしょう': 'Will likely',
    'ことに': 'Have to',
    'ことにしました': 'Decided to',
    'ことにします': 'Will decide to',
    'ことにした': 'Decided to',
    'ことがない': 'Have never',
    'ことなく': 'Without',
    'ことなので': 'So',
    'ことから': 'Because',
    'ことまで': 'Even',
    'ことより': 'More than',
    'ことなく': 'Without even',
    'ことに': 'In',
    'ことに': 'Specifically',
    
    // Hiragana expressions related to events
    'うえで': 'Upon',
    'うえで': 'Based on',
    'ください': 'Please',
    'くださいね': 'Please ok',
    'ください': 'Please do',
    'やってください': 'Please do',
    'など': 'Such as',
    'など': 'Etc',
    'いただく': 'To receive',
    'いただける': 'Can receive',
    'ていただき': 'Accepting',
    'ていただく': 'To have someone',
    'いただきましたら': 'If you would',
    'よろしくお願い': 'Thank you',
    'よろしくお願いします': 'Thank you very much',
    'よろしく': 'Best regards',
    'お願いします': 'Please',
    'お願いいたします': 'Please',
    'と思います': 'I think',
    'と思われます': 'I believe',
    'と思われる': 'Seems to',
    'と申します': 'Is called',
    'と申し': 'Named',
    'と異なります': 'Differs from',
    'と異なる': 'Different from',
    'ば': 'If',
    'ばならない': 'Must',
    'ばならません': 'Must',
    'ばならなかった': 'Had to',
    'ばいい': 'Should',
    'ばいいのに': 'Should have',
    'ばよかった': 'Should have',
    'ばいいのになあ': 'I wish',
    'ばいいのに': 'If only',
    
    // More hiragana sentence enders and particles
    'ね': 'Right',
    'よ': 'You know',
    'よね': 'Right',
    'な': 'Look',
    'なあ': 'Really',
    'わ': 'Is',
    'か': 'Or',
    'かな': 'I wonder',
    'かなあ': 'I really wonder',
    'か': 'Question',
    'や': 'Or',
    'や': 'And things',
    'やら': 'Or something',
    'も': 'Also',
    'も': 'Even',
    'ぞ': 'Emphatic',
    'けれど': 'But',
    'けれども': 'However',
    'けど': 'But',
    'けれ': 'But',
    'ても': 'Even if',
    'ても': 'Even though',
    'さえ': 'Even',
    'すら': 'Even',
    'まで': 'Until',
    'まで': 'As far as',
    'から': 'Because',
    'から': 'Since',
    'から': 'After',
    'から': 'From',
    'ので': 'Because',
    'ので': 'So',
    'のに': 'Despite',
    'のに': 'Yet',
    'のに': 'Even though',
    'ながら': 'While',
    'ながら': 'Although',
    'つつ': 'While',
    'ばかり': 'Only',
    'ばかり': 'Just',
    'ばかりか': 'Not only',
    'ばかりでなく': 'Not only',
    'のは': 'The fact that',
    'のは': 'Is',
    'のです': 'Is',
    'のだ': 'Is',
    'のだろう': 'I guess',
    'のだった': 'Was',
    'のだから': 'So',
    'のに': 'To',
    'のに': 'Yet',
    'の': 'Of',
    'の': 'Possessive',
    
    // Special event-related hiragana
    'こど': 'This',
    'ことは': 'As for',
    'ことも': 'Also',
    'ことが': 'That',
    'こそ': 'Emphasis',
    'こそが': 'Emphasis',
    'こそは': 'This time',
    'この': 'This',
    'この': 'These',
    'そこで': 'Therefore',
    'そこで': 'There',
    'それで': 'So',
    'それで': 'That way',
    'それでも': 'Still',
    'それでも': 'Anyway',
    'あこで': 'There',
    'あれ': 'That',
    'どれ': 'Which',
    'どの': 'Which',
    'どうしても': 'No matter what',
    'どうしても': 'Absolutely',
    'どうしても': 'Really',
    'どうぞ': 'Please',
    'どうぞ': 'Go ahead',
    'どう': 'How',
    'どう': 'What',
    'どう': 'In what way',
  };

  let result = text;
  // Sort by length (longest first) to avoid partial replacements
  const sortedKeys = Object.keys(translations).sort((a, b) => b.length - a.length);
  
  sortedKeys.forEach(jp => {
    // Escape special regex characters
    const escaped = jp.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const regex = new RegExp(escaped, 'gi');
    result = result.replace(regex, translations[jp]);
  });

  return result;
}
